# $ docker run -d --network minha-bridge --name meu-mongo mongo:4.4.6  
# $ docker run -d --network minha-bridge --name alurabooks -p 3000:3000 aluradocker/alura-books:1.0
# Esses dois comandos acima é o que está sendo feito aqui nesse arquivo

version: "3.9"
services:
  mongodb:
    image: mongo:4.4.6
    container_name: meu-mongo
    networks:
      - compose-bridge

  alurabooks:
    image: aluradocker/alura-books:1.0
    container_name: alurabooks
    networks:
      - compose-bridge
    ports:
      - 3000:3000
    depends_on:
      - mongodb

networks:
  compose-bridge:
    driver: bridge
